title = "ribbity-workshops"
site_name = "Data Intensive Biology Workshops"
site_url = "http://dib-lab.github.io/ribbity-workshops/"
github_repo = "dib-lab/ribbity-workshops"

add_pages = [ "index.md", "examples.md", "labels.md" ]

github_username = 'dib-lab'

issues_dump = 'ribbity-docs.dmp'

issue_title_prefix = 'Workshop: '